// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYd1IBvjEoARes0jUNGXL0JkEOCxn7dkY',
    appId: '1:371520711363:web:c7efd43c44b812c3551076',
    messagingSenderId: '371520711363',
    projectId: 'flutterauth-ac051',
    authDomain: 'flutterauth-ac051.firebaseapp.com',
    storageBucket: 'flutterauth-ac051.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuAg2OJqj0Hp8uiobqRcZ1P2hfOaonnb8',
    appId: '1:371520711363:android:b0137579be6376fa551076',
    messagingSenderId: '371520711363',
    projectId: 'flutterauth-ac051',
    storageBucket: 'flutterauth-ac051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqiyo3V3bstRBBCIQI77RXCgz9xeIYN_A',
    appId: '1:371520711363:ios:f4fe47b02681eac1551076',
    messagingSenderId: '371520711363',
    projectId: 'flutterauth-ac051',
    storageBucket: 'flutterauth-ac051.appspot.com',
    iosBundleId: 'com.example.flutterauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqiyo3V3bstRBBCIQI77RXCgz9xeIYN_A',
    appId: '1:371520711363:ios:f4fe47b02681eac1551076',
    messagingSenderId: '371520711363',
    projectId: 'flutterauth-ac051',
    storageBucket: 'flutterauth-ac051.appspot.com',
    iosBundleId: 'com.example.flutterauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYd1IBvjEoARes0jUNGXL0JkEOCxn7dkY',
    appId: '1:371520711363:web:2337ba3e3658183d551076',
    messagingSenderId: '371520711363',
    projectId: 'flutterauth-ac051',
    authDomain: 'flutterauth-ac051.firebaseapp.com',
    storageBucket: 'flutterauth-ac051.appspot.com',
  );
}
